# Generated by Django 4.1.5 on 2023-01-26 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensorwin',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 21, 10, 39, 566234, tzinfo=datetime.timezone.utc), verbose_name='Дата снятия счетчика'),
        ),
    ]
