# Generated by Django 4.1.5 on 2023-01-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='description',
        ),
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
