# Generated by Django 4.1.5 on 2023-01-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0002_remove_address_description_address_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='vend.address')),
            ],
            options={
                'verbose_name': 'Аппарат',
                'verbose_name_plural': 'Аппараты',
            },
        ),
    ]
